config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :wikis
  resources :charges, only: [:new, :create, :update]

  devise_for :models
  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :lockable

  def self.up
    create_table(:admins) do |t|
      t.string :email,              :null => false, :default => ""
      t.string :encrypted_password, :null => false, :default => ""
      t.integer  :sign_in_count, :default => 0
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.string   :current_sign_in_ip
      t.string   :last_sign_in_ip
      t.integer  :failed_attempts, :default => 0 # Only if lock strategy is :failed_attempts
      t.string   :unlock_token # Only if unlock strategy is :email or :both
      t.datetime :locked_at
      t.timestamps
    end
  end

  def self.down
    drop_table :admins
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user, dependent: :destroy

  def collaborators
    WikiCollaborator.where(wiki_id: id)
  end
end

app/models/wiki_collaborator.rb
class WikiCollaborator < ActiveRecord::Base
  def self.wikis
    Wiki.where(id: pluck(:wiki_id))
  end

  def self.users
    User.where(id: pluck(:user_id))
  end

  def wiki
    Wiki.find(wiki_id)
  end

  def user
    User.find(user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  include ChargesHelper
  def create
    Stripe.api_key = "sk_test_Xo8AAESZajnBsYkxzYTQcgzl"

    # plan = stripe.Plan.create(
    #   name="Basic Plan",
    #   id="basic-monthly",
    #   interval="month",
    #   currency="usd",
    #   amount=0,
    # )
    #
    # plan = Stripe::Plan.create(
    #   :name => "Premium Plan",
    #   :id => "premium-monthly",
    #   :interval => "month",
    #   :currency => "usd",
    #   :amount => 1000,
    # )

    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    subscription = Stripe::Subscription.create(
      :customer => customer.id,
      :plan => "premium-monthly"
    )

    current_user.sub_id = subscription.id
    current_user.is_premium = true
    current_user.save(validate: false)
    # Where the real magic happens
    # charge = Stripe::Charge.create(
    #   customer: customer.id, # Note -- this is NOT the user_id in your app
    #   amount: Amount.default,
    #   description: "Premium Membership - #{current_user.email}",
    #   currency: 'usd'
    # )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to "/" # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: Amount.default
   }
  end

  def update()
    sub_id = params[:id]
    Stripe.api_key = "sk_test_Xo8AAESZajnBsYkxzYTQcgzl"

    subscription = Stripe::Subscription.retrieve(sub_id)
    subscription.plan = "basic-monthly"
    subscription.save

    current_user.is_premium = false
    current_user.sub_id = nil
    current_user.save()

    wikis = Wiki.where("private = ? and user_id = ?", true, current_user.id)
    wikis.each do |w|
      w.private = false
      w.save()
    end

    flash[:notice] = "All of your private wikis have been made public."
    redirect_to "/"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    user_id = -999
    if current_user != nil
      user_id = current_user.id
    end

    @wikis = policy_scope(Wiki)
    @wikis = Wiki.where("private IS NULL or private = ? or user_id = ?", false, user_id)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    @wiki.private = params[:wiki][:private]
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user_id = current_user.id



    if @wiki.save
      redirect_to @wiki
    else
      flash[:notice] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    require 'redcarpet'
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user_id = current_user.id
    @wiki.collaborators = params[:wiki][:collaborators]

    

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
  class Amount
    def self.default
      1000
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$10.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $10.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="1000"
          data-locale="auto"></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", wikis_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
         Signed in as: <strong><%= current_user.email %></strong> |
         <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
       <% else %>
         <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
       <% end %>
    </ul>
    <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<div class="about">
  <h3>About Blocipedia</h3>
  <br>
  <p>Blocipedia is a project that replicates wikipedia, a free online encyclopedia that is written by the people who use it. This is a project of Bloc Academy's backend web development course. Blocipedia is built with the Ruby on Rails framework.</p>
</div>

app/views/welcome/index.html.erb
<div class="welcome_title">
  <h1>Blocipedia</h1>
  <h5>Because sharing is caring and learning is earning.</h5>
</div>
<div class="sign_up">
  <div class="sign_up_button">
    <h3>Join the Blocipedia community today!</h3>
    <br>
    <button type="button">
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
    </button>
  </div>
  <div class="account_types">
    <p><strong>Standard</strong> : Unconstipate your brain and unleash all that pent up knowledge  by creating as many wikis as your heart desires.</p>
    <p><strong>Premium</strong> : Because a standard account just isn't enough. Premium accounts allow you to create private wikis, which will lead to online cliques and potentially encourage cyber bullying.</p>
  </div>
</div>

app/views/wikis/_collaborators.html.erb
<% if current_user != nil && current_user.is_premium && @wiki.private %>
  <div class="form-group">
    <%= f.label :collaborators, class: 'checkbox' do %>
      <%= f.text_field :collaborators, class: 'form-control', placeholder: "Collaborators" %>
      <%= form_tag({:collaborators => 'create'}, {:id => @user.id}) %>
    <% end %>
  </div>
<% end %>

app/views/wikis/_premium.html.erb
<% if current_user != nil && current_user.is_premium %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>You must have a bachelor's degree to post new wikis.</li>
      <li>You must enter new wikis with your eyes closed.</li>
      <li>You must drive an economical vehicle, regardless if you are creating new wikis.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <div class="col-md-8">
        <%= render partial: 'premium', locals: { f: f } %>
        <%= render partial: 'collaborators', locals: { f: f } %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis<h2>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>You must have a bachelor's degree to post new wikis.</li>
      <li>You must enter new wikis with your eyes closed.</li>
      <li>You must drive an economical vehicle, regardless if you are creating new wikis.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <div class="col-md-8">
        <%= render partial: 'premium', locals: { f: f } %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>